kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs-system
provisioner: ceph.com/cephfs
parameters:
  monitors: 192.168.1.100:6789,192.168.1.110:6789,192.168.1.120:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: "kube-system"
  claimRoot: /volumes/kubernetes
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: 192.168.1.100:6789,192.168.1.110:6789,192.168.1.120:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: "default"
  claimRoot: /volumes/kubernetes